version: "3.8"

services:
  cowrie-honeypot:
    build: .
    container_name: cowrie-container
    image: cowrie
    ports:
      - "2222:2222"
      - "2223:2223"
    volumes:
      - ./cowrie-logs:/home/cowrie/cowrie/var/log/cowrie # Mounts local directory to container directory
    restart: unless-stopped # Restart the container automatically on failure
